version: '3.5'

services:
  db:
    image: postgres:11
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER:-prisma}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-prisma}
    volumes:
      - postgres:/var/lib/postgresql/data

  prisma:
    build: prisma
    restart: on-failure
    ports:
    - "${PRISMA_PORT:-4466}:4466"
    env_file: .env
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: ${DB_CONNECTOR:-postgres}
            database: ${DB_DATABASE:-prisma}
            host: ${DB_HOST:-db}
            port: ${DB_PORT:-5432}
            user: ${DB_USER:-prisma}
            password: ${DB_PASSWORD:-prisma}

volumes:
  postgres:
